# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#Publishing-using-gradle

name: Gradle Package

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file
        cache: gradle

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
      with:
         gradle-version: "8.8"

    - name: Build with Gradle
      run: gradle build


    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Package
        path: build/libs


    - name: mc-publish

      uses: Kir-Antipov/mc-publish@v3.3.0
      with:

    # The tag name for the release where assets will be uploaded.
        github-tag: AutoGenerated # optional, default is ${undefined}
    # Set to true to generate a changelog automatically for this release; false otherwise. Ignored if the GitHub Release already exists.
        github-generate-changelog: true # optional, default is ${undefined}
    # Set to true to create a draft release; false otherwise. Ignored if the GitHub Release already exists.
        github-draft: true # optional, default is ${undefined}
        github-token: ${{ secrets.GITHUB_TOKEN }}
